# Basic usage of geo3d

In [1]:
from geo3d import frame_wizard, Vector, Point, RotationMatrix, Frame, transformation_between_frames
import numpy as np

## Frame creation

### Manual Frame cration
Manually create frame from given rotation Euler angles and translation vector.

In [2]:
rot = RotationMatrix.from_euler_angles('xyz', [-70.89339465, -74.20683095,  45], degrees=True)
vec = Vector([3,4,6])
Frame(rot,vec)

### The Frame Wizard
Create two frames using a Frame Wizard (comparable to the one in Spatial Analyzer).
Frames are defined as transformations starting from a unit frame (no translation and rotation).

In [3]:
fa = frame_wizard(Vector([1,1,5]),Vector([1,2,0]), 'x', 'y', origin=[3,4,6])
fb = frame_wizard(Vector([1,2,0]),Vector([-1,-1,-5]), 'x', 'y', origin=[6,4,6])

In [4]:
fa

In [5]:
print(fb)

<Frame instance at 693358400>
rotation
[[ 0.4472136  -0.07968191 -0.89087081]
 [ 0.89442719  0.03984095  0.4454354 ]
 [ 0.         -0.99602384  0.08908708]]
Fixed angles (xyz, extrinsic, deg.)
[-84.8889103    0.          63.43494882]
Euler angles (XYZ, intrinsic, deg.)
[-78.69006753 -62.98287678  10.10261179]
translation
[6 4 6]


They have a rotation and translation component:

In [6]:
fb.translation

<Vector at 81280400> [6 4 6]

In [7]:
fb.rotation

The rotation can be expressed as Euler angles.

In [9]:
fb.euler_angles('xyz', degrees='True')

array([-84.8889103 ,   0.        ,  63.43494882])

## Frame to frame transformations 

A frame can be expressed in a different frame. 

In [10]:
fb.express_in_frame(fa)

This yields the frame-to-frame transformation from fA to fB, represented in fA.

The same frame-to-frame transformation matrix, but given in the original (unit) frame is 

In [12]:
transformation_between_frames(fa,fb)

## Expression of vectors and points in frames

Express a vector given in `original_frame` in a new frame.

In [13]:
Vector([1,3,0]).express_in_frame(fa, original_frame=fb)

<Vector at 738522688> [-0.29436552  1.00784573 -2.98288383]

Express a point given in `original_frame` in a new frame.

In [14]:
Point([5,3,20]).express_in_frame(fa, original_frame=fb)

<Point at 738357648> [13.06331157 17.35174152 -1.12559193]