# Basic usage of geo3d

In [1]:
from geo3d import frame_wizard, Vector, Point, RotationMatrix, Frame, transformation_between_frames
import numpy as np

## Frame creation

### Manual Frame cration
Manually create frame from given rotation Euler angles and translation vector.

In [2]:
rot = RotationMatrix.from_euler_angles('xyz', [-70.89339465, -74.20683095,  45], degrees=True)
vec = Vector([3,4,6])
Frame(rot,vec)

&lt;geo3d.geometry.Frame at 0x23a9cae8040&gt;

### The Frame Wizard
Create two frames using a Frame Wizard (comparable to the one in Spatial Analyzer).
Frames are defined as transformations starting from a unit frame (no translation and rotation).

In [3]:
# rotation only from UnitFrame
fa = frame_wizard(Vector([1, 1, 0]), Vector([1, -1, 0]), "x", "y", origin=[0, 0, 0])
# translation only from UnitFrame
fb = frame_wizard(Vector([1, 0, 0]), Vector([0, 1, 0]), "x", "y", origin=[1, 1, 4])
# rotation and translation from UnitFrame
fc = frame_wizard(Vector([1, 1, 0]), Vector([1, -1, 0]), "x", "y", origin=[1, 1, 4])

In [4]:
fa

&lt;geo3d.geometry.Frame at 0x23a9cae8c40&gt;

In [5]:
print(fb)

&lt;Frame instance at 2450760043920&gt;
rotation
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
Fixed angles (xyz, extrinsic, deg.)
[0. 0. 0.]
Euler angles (XYZ, intrinsic, deg.)
[0. 0. 0.]
translation
[1 1 4]


They have a rotation and translation component:

In [6]:
fc.translation

&lt;Vector at 2452389237424&gt; [1 1 4]

In [7]:
fc.rotation

&lt;geo3d.geometry.RotationMatrix at 0x23afdca1280&gt;

The rotation can be expressed as Euler angles.

In [8]:
fc.euler_angles('xyz', degrees='True')

array([180.,   0.,  45.])

## Frame to frame transformations 

A frame can be expressed in a different frame. 

In [9]:
fb.express_in_frame(fa)

&lt;geo3d.geometry.Frame at 0x23afdca1940&gt;

This yields the frame-to-frame transformation from fA to fB, represented in fA.

The same frame-to-frame transformation matrix, but given in the original (unit) frame is 

In [10]:
transformation_between_frames(fa, fb)

&lt;geo3d.geometry.Frame at 0x23afdca1340&gt;

## Expression of vectors and points in frames

Express a vector given in `original_frame` in a new frame.

In [11]:
Vector([1,3,0]).express_in_frame(fa, original_frame=fb)

&lt;Vector at 2450798500736&gt; [ 2.82842712 -1.41421356  0.        ]

Express a point given in `original_frame` in a new frame.

In [12]:
Point([5,3,20]).express_in_frame(fa, original_frame=fb)

&lt;Point at 2452389210528&gt; [  7.07106781   1.41421356 -24.        ]