# Basic usage of geo3d

In [1]:
from geo3d import frame_wizard, Vector, Point, RotationMatrix, Frame, transformation_between_frames
import numpy as np

## Frame creation

### Manual Frame cration
Manually create frame from given rotation Euler angles and translation vector.

In [2]:
rot = RotationMatrix.from_euler_angles('xyz', [-70.89339465, -74.20683095,  45], degrees=True)
vec = Vector([3,4,6])
Frame(rot,vec)

&lt;geo3d.geometry.Frame at 0x1319b102a90&gt;

### The Frame Wizard
Create two frames using a Frame Wizard (comparable to the one in Spatial Analyzer).
Frames are defined as transformations starting from a unit frame (no translation and rotation).

In [3]:
fa = frame_wizard(Vector([1,1,5]),Vector([1,2,0]), 'x', 'y', origin=[3,4,6])
fb = frame_wizard(Vector([1,2,0]),Vector([-1,-1,-5]), 'x', 'y', origin=[6,4,6])

In [4]:
fa

&lt;geo3d.geometry.Frame at 0x131bc22d700&gt;

In [5]:
fb.SA_pastable_string()

&#39;0.447213595500 -0.079681907289 -0.890870806375 6.000000000000 0.894427191000 0.039840953644 0.445435403187 4.000000000000 0.000000000000 -0.996023841112 0.089087080637 6.000000000000 0.000000000000 0.000000000000 0.000000000000 1.000000000000&#39;

In [6]:
print(fb)

&lt;Frame instance at 1313121747968&gt;
rotation
[[ 0.4472136  -0.07968191 -0.89087081]
 [ 0.89442719  0.03984095  0.4454354 ]
 [ 0.         -0.99602384  0.08908708]]
Fixed angles (xyz, extrinsic, deg.)
[-84.8889103    0.          63.43494882]
Euler angles (XYZ, intrinsic, deg.)
[-78.69006753 -62.98287678  10.10261179]
translation
[6 4 6]


They have a rotation and translation component:

In [7]:
fb.translation

&lt;Vector at 1312566554000&gt; [6 4 6]

In [8]:
fb.rotation

&lt;geo3d.geometry.RotationMatrix at 0x1319b0fb8b0&gt;

The rotation can be expressed as Euler angles.

In [9]:
fb.euler_angles('xyz', degrees='True')

array([-84.8889103 ,   0.        ,  63.43494882])

## Frame to frame transformations 

A frame can be expressed in a different frame. 

In [10]:
fb.express_in_frame(fa)

&lt;geo3d.geometry.Frame at 0x1319b102190&gt;

This yields the frame-to-frame transformation from fA to fB, represented in fA.

The same frame-to-frame transformation matrix, but given in the original (unit) frame is 

&lt;geo3d.geometry.Frame at 0x1a85af965b0&gt;

## Expression of vectors and points in frames

Express a vector given in `original_frame` in a new frame.

In [11]:
Vector([1,3,0]).express_in_frame(fa, original_frame=fb)

&lt;Vector at 1313123721280&gt; [-2.64007646e+00  1.74068845e+00 -3.09615454e-17]

Express a point given in `original_frame` in a new frame.

In [13]:
Point([5,3,20]).express_in_frame(fa, original_frame=fb)

&lt;Point at 1312570216016&gt; (-1.029930631312456, 6.839482384334699, 17.327387580875754)